chore(deps): update module github.com/lib/pq to v1.12.3 (8.19) (#6099)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [github.com/lib/pq](https://redirect.github.com/lib/pq) | indirect |
minor | `v1.10.9` -> `v1.12.3` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>lib/pq (github.com/lib/pq)</summary>

###
[`v1.12.3`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1123-2026-04-03)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.12.2...v1.12.3)

- Send datestyle startup parameter, improving compatbility with database
engines
that use a different default datestyle such as EnterpriseDB
([#&#8203;1312]).

[#&#8203;1312]: https://redirect.github.com/lib/pq/pull/1312

###
[`v1.12.2`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1122-2026-04-02)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.12.1...v1.12.2)

- Treat io.ErrUnexpectedEOF as driver.ErrBadConn so database/sql
discards the
connection. Since v1.12.0 this could result in permanently broken
connections,
especially with CockroachDB which frequently sends partial messages
([#&#8203;1299]).

[#&#8203;1299]: https://redirect.github.com/lib/pq/pull/1299

###
[`v1.12.1`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1121-2026-03-30)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.12.0...v1.12.1)

- Look for pgpass file in ~/.pgpass instead of ~/.postgresql/pgpass
([#&#8203;1300]).

-   Don't clear password if directly set on pq.Config ([#&#8203;1302]).

[#&#8203;1300]: https://redirect.github.com/lib/pq/pull/1300

[#&#8203;1302]: https://redirect.github.com/lib/pq/pull/1302

###
[`v1.12.0`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1120-2026-03-18)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.11.2...v1.12.0)

- The next release may change the default sslmode from `require` to
`prefer`.
    See [#&#8203;1271] for details.

- `CopyIn()` and `CopyInToSchema()` have been marked as deprecated.
These are
simple query builders and not needed for `COPY [..] FROM STDIN` support
(which
    is *not* deprecated). ([#&#8203;1279])

        // Old
        tx.Prepare(CopyIn("temp", "num", "text", "blob", "nothing"))

        // Replacement
        tx.Prepare(`copy temp (num, text, blob, nothing) from stdin`)

##### Features

-   Support protocol 3.2, and the `min_protocol_version` and
    `max_protocol_version` DSN parameters ([#&#8203;1258]).

-   Support `sslmode=prefer` and `sslmode=allow` ([#&#8203;1270]).

- Support `ssl_min_protocol_version` and `ssl_max_protocol_version`
([#&#8203;1277]).

- Support connection service file to load connection details
([#&#8203;1285]).

- Support `sslrootcert=system` and use `~/.postgresql/root.crt` as the
default
    value of sslrootcert ([#&#8203;1280], [#&#8203;1281]).

- Add a new `pqerror` package with PostgreSQL error codes
([#&#8203;1275]).

    For example, to test if an error is a UNIQUE constraint violation:

if pqErr, ok := errors.AsType[*pq.Error](err); ok && pqErr.Code ==
pqerror.UniqueViolation {
            log.Fatalf("email %q already exsts", email)
        }

To make this a bit more convenient, it also adds a `pq.As()` function:

        pqErr := pq.As(err, pqerror.UniqueViolation)
        if pqErr != nil {
            log.Fatalf("email %q already exsts", email)
        }

##### Fixes

- Fix SSL key permission check to allow modes stricter than
[0600/0640#1265](https://redirect.github.com/0600/0640/issues/1265)
([#&#8203;1265]).

-   Fix Hstore to work with binary parameters ([#&#8203;1278]).

- Clearer error when starting a new query while pq is still processing
another
    query ([#&#8203;1272]).

- Send intermediate CAs with client certificates, so they can be signed
by an
    intermediate CA ([#&#8203;1267]).

-   Use `time.UTC` for UTC aliases such as `Etc/UTC` ([#&#8203;1282]).

[#&#8203;1258]: https://redirect.github.com/lib/pq/pull/1258

[#&#8203;1265]: https://redirect.github.com/lib/pq/pull/1265

[#&#8203;1267]: https://redirect.github.com/lib/pq/pull/1267

[#&#8203;1270]: https://redirect.github.com/lib/pq/pull/1270

[#&#8203;1271]: https://redirect.github.com/lib/pq/pull/1271

[#&#8203;1272]: https://redirect.github.com/lib/pq/pull/1272

[#&#8203;1275]: https://redirect.github.com/lib/pq/pull/1275

[#&#8203;1277]: https://redirect.github.com/lib/pq/pull/1277

[#&#8203;1278]: https://redirect.github.com/lib/pq/pull/1278

[#&#8203;1279]: https://redirect.github.com/lib/pq/pull/1279

[#&#8203;1280]: https://redirect.github.com/lib/pq/pull/1280

[#&#8203;1281]: https://redirect.github.com/lib/pq/pull/1281

[#&#8203;1282]: https://redirect.github.com/lib/pq/pull/1282

[#&#8203;1283]: https://redirect.github.com/lib/pq/pull/1283

[#&#8203;1285]: https://redirect.github.com/lib/pq/pull/1285

###
[`v1.11.2`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1112-2026-02-10)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.11.1...v1.11.2)

This fixes two regressions:

- Don't send startup parameters if there is no value, improving
compatibility
    with Supavisor ([#&#8203;1260]).

- Don't send `dbname` as a startup parameter if `database=[..]` is used
in the
connection string. It's recommended to use dbname=, as database= is not
a
libpq option, and only worked by accident previously. ([#&#8203;1261])

[#&#8203;1260]: https://redirect.github.com/lib/pq/pull/1260

[#&#8203;1261]: https://redirect.github.com/lib/pq/pull/1261

###
[`v1.11.1`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1111-2026-01-29)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.11.0...v1.11.1)

This fixes two regressions present in the v1.11.0 release:

-   Fix build on 32bit systems, Windows, and Plan 9 ([#&#8203;1253]).

- Named \[]byte types and pointers to \[]byte (e.g. `*[]byte`,
`json.RawMessage`)
    would be treated as an array instead of bytea ([#&#8203;1252]).

[#&#8203;1252]: https://redirect.github.com/lib/pq/pull/1252

[#&#8203;1253]: https://redirect.github.com/lib/pq/pull/1253

###
[`v1.11.0`](https://redirect.github.com/lib/pq/blob/HEAD/CHANGELOG.md#v1110-2026-01-28)

[Compare
Source](https://redirect.github.com/lib/pq/compare/v1.10.9...v1.11.0)

This version of pq requires Go 1.21 or newer.

pq now supports only maintained PostgreSQL releases, which is PostgreSQL
14 and
newer. Previously PostgreSQL 8.4 and newer were supported.

##### Features

- The `pq.Error.Error()` text includes the position of the error (if
reported
    by PostgreSQL) and SQLSTATE code ([#&#8203;1219], [#&#8203;1224]):

pq: column "columndoesntexist" does not exist at column 8 (42703)
        pq: syntax error at or near ")" at position 2:71 (42601)

- The `pq.Error.ErrorWithDetail()` method prints a more detailed
multiline
message, with the Detail, Hint, and error position (if any)
([#&#8203;1219]):

        ERROR:   syntax error at or near ")" (42601)
        CONTEXT: line 12, column 1:

             10 |     name           varchar,
             11 |     version        varchar,
             12 | );
                  ^

- Add `Config`, `NewConfig()`, and `NewConnectorConfig()` to supply
connection
    details in a more structured way ([#&#8203;1240]).

-   Support `hostaddr` and `$PGHOSTADDR` ([#&#8203;1243]).

- Support multiple values in `host`, `port`, and `hostaddr`, which are
each
tried in order, or randomly if `load_balance_hosts=random` is set
([#&#8203;1246]).

- Support `target_session_attrs` connection parameter ([#&#8203;1246]).

- Support [`sslnegotiation`][sslnegotiation] to use SSL without
negotiation ([#&#8203;1180]).

- Allow using a custom `tls.Config`, for example for encrypted keys
([#&#8203;1228]).

- Add `PQGO_DEBUG=1` print the communication with PostgreSQL to stderr,
to aid
    in debugging, testing, and bug reports ([#&#8203;1223]).

- Add support for NamedValueChecker interface ([#&#8203;1125],
[#&#8203;1238]).

##### Fixes

- Match HOME directory lookup logic with libpq: prefer $HOME over
/etc/passwd,
    ignore ENOTDIR errors, and use APPDATA on Windows ([#&#8203;1214]).

- Fix `sslmode=verify-ca` verifying the hostname anyway when connecting
to a DNS
    name (rather than IP) ([#&#8203;1226]).

- Correctly detect pre-protocol errors such as the server not being able
to fork
    or running out of memory ([#&#8203;1248]).

- Fix build with wasm ([#&#8203;1184]), appengine ([#&#8203;745]), and
Plan 9 ([#&#8203;1133]).

- Deprecate and type alias `pq.NullTime` to `sql.NullTime`
([#&#8203;1211]).

- Enforce integer limits of the Postgres wire protocol ([#&#8203;1161]).

- Accept the `passfile` connection parameter to override `PGPASSFILE`
([#&#8203;1129]).

-   Fix connecting to socket on Windows systems ([#&#8203;1179]).

- Don't perform a permission check on the .pgpass file on Windows
([#&#8203;595]).

-   Warn about incorrect .pgpass permissions ([#&#8203;595]).

-   Don't set extra_float_digits ([#&#8203;1212]).

-   Decode bpchar into a string ([#&#8203;949]).

- Fix panic in Ping() by not requiring CommandComplete or
EmptyQueryResponse in
    simpleQuery() ([#&#8203;1234])

- Recognize bit/varbit ([#&#8203;743]) and float types ([#&#8203;1166])
in ColumnTypeScanType().

- Accept `PGGSSLIB` and `PGKRBSRVNAME` environment variables
([#&#8203;1143]).

- Handle ErrorResponse in readReadyForQuery and return proper error
([#&#8203;1136]).

- Detect COPY even if the query starts with whitespace or comments
([#&#8203;1198]).

- CopyIn() and CopyInSchema() now work if the list of columns is empty,
in which
    case it will copy all columns ([#&#8203;1239]).

- Treat nil \[]byte in query parameters as nil/NULL rather than `""`
([#&#8203;838]).

- Accept multiple authentication methods before checking AuthOk, which
improves
    compatibility with PgPool-II ([#&#8203;1188]).

[`sslnegotiation`]:
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLNEGOTIATION

[#&#8203;595]: https://redirect.github.com/lib/pq/pull/595

[#&#8203;745]: https://redirect.github.com/lib/pq/pull/745

[#&#8203;743]: https://redirect.github.com/lib/pq/pull/743

[#&#8203;838]: https://redirect.github.com/lib/pq/pull/838

[#&#8203;949]: https://redirect.github.com/lib/pq/pull/949

[#&#8203;1125]: https://redirect.github.com/lib/pq/pull/1125

[#&#8203;1129]: https://redirect.github.com/lib/pq/pull/1129

[#&#8203;1133]: https://redirect.github.com/lib/pq/pull/1133

[#&#8203;1136]: https://redirect.github.com/lib/pq/pull/1136

[#&#8203;1143]: https://redirect.github.com/lib/pq/pull/1143

[#&#8203;1161]: https://redirect.github.com/lib/pq/pull/1161

[#&#8203;1166]: https://redirect.github.com/lib/pq/pull/1166

[#&#8203;1179]: https://redirect.github.com/lib/pq/pull/1179

[#&#8203;1180]: https://redirect.github.com/lib/pq/pull/1180

[#&#8203;1184]: https://redirect.github.com/lib/pq/pull/1184

[#&#8203;1188]: https://redirect.github.com/lib/pq/pull/1188

[#&#8203;1198]: https://redirect.github.com/lib/pq/pull/1198

[#&#8203;1211]: https://redirect.github.com/lib/pq/pull/1211

[#&#8203;1212]: https://redirect.github.com/lib/pq/pull/1212

[#&#8203;1214]: https://redirect.github.com/lib/pq/pull/1214

[#&#8203;1219]: https://redirect.github.com/lib/pq/pull/1219

[#&#8203;1223]: https://redirect.github.com/lib/pq/pull/1223

[#&#8203;1224]: https://redirect.github.com/lib/pq/pull/1224

[#&#8203;1226]: https://redirect.github.com/lib/pq/pull/1226

[#&#8203;1228]: https://redirect.github.com/lib/pq/pull/1228

[#&#8203;1234]: https://redirect.github.com/lib/pq/pull/1234

[#&#8203;1238]: https://redirect.github.com/lib/pq/pull/1238

[#&#8203;1239]: https://redirect.github.com/lib/pq/pull/1239

[#&#8203;1240]: https://redirect.github.com/lib/pq/pull/1240

[#&#8203;1243]: https://redirect.github.com/lib/pq/pull/1243

[#&#8203;1246]: https://redirect.github.com/lib/pq/pull/1246

[#&#8203;1248]: https://redirect.github.com/lib/pq/pull/1248

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* 1 * * 1-5" (UTC), Automerge - At
any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Renovate
Bot](https://redirect.github.com/renovatebot/renovate).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEwNy4wIiwidGFyZ2V0QnJhbmNoIjoiOC4xOSIsImxhYmVscyI6WyJUZWFtOlNlY3VyaXR5LUNsb3VkIFNlcnZpY2VzIiwiYmFja3BvcnQtc2tpcCIsImRlcGVuZGVuY2llcyIsInJlbm92YXRlIiwicmVub3ZhdGUtYXV0by1hcHByb3ZlIl19-->

Co-authored-by: elastic-renovate-prod[bot] <174716857+elastic-renovate-prod[bot]@users.noreply.github.com>